version: '2'

services:
  web:
    image: nginx:latest
    container_name: "${CONTAINER_NGINX}"
    ports:
      - "80:80"
    env_file: .env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    volumes_from:
      - wordpress-data

  # php
  php:  
    build: ./php/
    container_name: "${CONTAINER_PHP}"
    env_file: .env
    expose:
      - 9000
    links:
      - mysql
    volumes_from:
      - wordpress-data

  # mysql
  mysql:
    image: mysql:latest
    volumes_from:
      - mysql-data
    #ports:
    #  - "3306:3306"
    container_name: "${CONTAINER_MYSQL}"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
  
  # wordpress data
  wordpress-data:
    image: php:7.0-fpm
    container_name: "${CONTAINER_APP_DATA}"
    volumes:
      - ${SRC_APP_PERSISTENT}:/var/www/html
    command: "true"
  
  # mysql data
  mysql-data:
    image: mysql:latest
    container_name: "${CONTAINER_MYSQL_DATA}"
    volumes:
      - ${SRC_DB_PERSISTENT}:/var/lib/mysql
    command: "true"
  
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
